
import { asset } from '../../lib/asset'

const FILE_BASE = 'img'
const FOLDER_BASE = 'floder'

function fileUrl(value: string): string {
  if (value.includes('.')) return asset(`${FILE_BASE}/${value}`)
  return asset(`${FILE_BASE}/${value}.svg`)
}
function folderUrl(value: string): string {
  if (value.includes('.')) return asset(`${FOLDER_BASE}/${value}`)
  return asset(`${FOLDER_BASE}/${value}.svg`)
}


const FOLDER_BY_NAME: Record<string, string> = {
  '.git': 'folder-git',
  '.github': 'folder-github',
  '.gitlab': 'folder-gitlab',
  '.vscode': 'folder-vscode',
  '.cursor': 'folder-cursor',
  '.docker': 'folder-docker',
  '.expo': 'folder-expo',
  '.next': 'folder-cognitive',
  '.nuxt': 'folder-cognitive',
  '.husky': 'folder-config',
  '.idea': 'folder-config',
  '.claude': 'folder-claude',

  src: 'folder-src',
  source: 'folder-src',
  app: 'folder-app',
  pages: 'folder-app',
  views: 'folder-layout',
  components: 'folder-react',
  layouts: 'folder-layout',
  layout: 'folder-layout',
  hooks: 'folder-hooks',
  utils: 'folder-utils',
  helpers: 'folder-helpers',
  lib: 'folder-shared',
  shared: 'folder-shared',
  core: 'folder-core',
  modules: 'folder-modules',
  models: 'folder-models',
  services: 'folder-services',
  service: 'folder-services',
  providers: 'folder-providers',
  context: 'folder-context',
  contexts: 'folder-context',
  constants: 'folder-constants',
  config: 'folder-config',
  configs: 'folder-config',
  configuration: 'folder-config',
  router: 'folder-router',
  routes: 'folder-router',
  middleware: 'folder-middleware',
  middlewares: 'folder-middleware',
  interceptors: 'folder-interceptors',
  interfaces: 'folder-interfaces',
  types: 'folder-interfaces',
  pipes: 'folder-pipes',
  effects: 'folder-effects',
  reducers: 'folder-reducer',
  selectors: 'folder-selector',
  facades: 'folder-facade',

  assets: 'folder-assets',
  static: 'folder-assets',
  public: 'folder-assets',
  images: 'folder-images',
  img: 'folder-images',
  fonts: 'folder-fonts',
  i18n: 'folder-i18n',
  locales: 'folder-i18n',
  locale: 'folder-i18n',
  translations: 'folder-i18n',
  documents: 'folder-documents',
  docs: 'folder-documents',

  build: 'folder-build',
  dist: 'folder-build',
  out: 'folder-build',
  output: 'folder-build',
  target: 'folder-target',

  node_modules: 'folder-node-modules',

  test: 'folder-cypress',
  tests: 'folder-cypress',
  __tests__: 'folder-cypress',
  e2e: 'folder-cypress',
  cypress: 'folder-cypress',
  android: 'folder-android',
  ios: 'folder-ios',

  scripts: 'folder-actions',
  actions: 'folder-actions',
  github: 'folder-github',
  gitlab: 'folder-gitlab',
  graphql: 'folder-graphql',
  prisma: 'folder-prisma',
  drizzle: 'folder-drizzle',
  sass: 'folder-sass',
  scss: 'folder-sass',
  styles: 'folder-sass',
  database: 'folder-database',
  db: 'folder-database',
  redis: 'folder-redis',
  mongo: 'folder-mongo',
  mongodb: 'folder-mongo',
  supabase: 'folder-supabase',
  firebase: 'folder-firebase',
  vercel: 'folder-vercel',
  aws: 'folder-aws',
  azure: 'folder-azure',
  nginx: 'folder-nginx',
  docker: 'folder-docker',
  bruno: 'folder-bruno',
  tauri: 'folder-tauri',
  expo: 'folder-expo',
  tina: 'folder-tina',
  gradle: 'folder-gradle',
  mail: 'folder-mail',
  emails: 'folder-mail'
}


const FILE_BY_NAME: Record<string, string> = {
  'package.json': 'npm',
  'package-lock.json': 'npm',
  'pnpm-lock.yaml': 'pnpm',
  'pnpm-workspace.yaml': 'pnpm',
  '.npmrc': 'npm',
  '.nvmrc': 'node',
  '.node-version': 'node',
  'yarn.lock': 'yarn',
  '.yarnrc': 'yarn',
  '.yarnrc.yml': 'yarn',
  'bun.lockb': 'bun',
  'bun.lock': 'bun',
  'bunfig.toml': 'bun',
  'deno.json': 'deno',
  'deno.jsonc': 'deno',
  'deno.lock': 'deno',

  'tsconfig.json': 'tsconfig',
  'tsconfig.node.json': 'tsconfig',
  'tsconfig.web.json': 'tsconfig',
  'tsconfig.app.json': 'tsconfig',
  'tsconfig.build.json': 'tsconfig',
  'jsconfig.json': 'tsconfig',

  'vite.config.ts': 'vite',
  'vite.config.js': 'vite',
  'vite.config.mjs': 'vite',
  'vite.config.cjs': 'vite',
  'vitest.config.ts': 'vitest',
  'vitest.config.js': 'vitest',
  'webpack.config.js': 'webpack',
  'webpack.config.ts': 'webpack',
  'webpack.config.mjs': 'webpack',
  'rspack.config.ts': 'rspack',
  'rspack.config.js': 'rspack',
  'rsbuild.config.ts': 'rsbuild',
  'rsbuild.config.js': 'rsbuild',
  'rslib.config.ts': 'rslib',
  'rollup.config.js': 'webpack',
  'rollup.config.ts': 'webpack',
  'rollup.config.mjs': 'webpack',
  'turbo.json': 'turborepo',
  'nx.json': 'nx',
  'gulpfile.js': 'gulp',
  'gulpfile.ts': 'gulp',
  'jest.config.js': 'jest',
  'jest.config.ts': 'jest',
  'jest.setup.js': 'jest',
  'jest.setup.ts': 'jest',
  'cypress.config.js': 'cypress',
  'cypress.config.ts': 'cypress',
  'cucumber.js': 'cucumber',

  '.eslintrc': 'eslint',
  '.eslintrc.js': 'eslint',
  '.eslintrc.cjs': 'eslint',
  '.eslintrc.json': 'eslint',
  '.eslintrc.yml': 'eslint',
  'eslint.config.js': 'eslint',
  'eslint.config.mjs': 'eslint',
  'eslint.config.ts': 'eslint',
  '.eslintignore': 'eslint',
  '.prettierrc': 'prettier',
  '.prettierrc.json': 'prettier',
  '.prettierrc.js': 'prettier',
  '.prettierrc.yml': 'prettier',
  'prettier.config.js': 'prettier',
  'prettier.config.cjs': 'prettier',
  '.prettierignore': 'prettier',
  'biome.json': 'biome',
  'biome.jsonc': 'biome',
  'rome.json': 'rome',
  '.stylelintrc': 'stylelint',
  '.stylelintrc.json': 'stylelint',
  '.stylelintrc.js': 'stylelint',
  '.stylelintignore': 'stylelint',
  'oxlint.json': 'oxlint',
  'oxlintrc.json': 'oxlint',
  '.knip.json': 'knip',
  'knip.json': 'knip',
  'knip.config.ts': 'knip',
  '.editorconfig': 'editorconfig',

  'next.config.js': 'next',
  'next.config.mjs': 'next',
  'next.config.ts': 'next',
  'nuxt.config.ts': 'nuxt',
  'nuxt.config.js': 'nuxt',
  'astro.config.ts': 'astro',
  'astro.config.mjs': 'astro',
  'svelte.config.js': 'svelte',
  'svelte.config.ts': 'svelte',
  'tauri.conf.json': 'tauri',
  'capacitor.config.ts': 'capacitor',
  'capacitor.config.json': 'capacitor',
  'tailwind.config.js': 'tailwind',
  'tailwind.config.ts': 'tailwind',
  'tailwind.config.cjs': 'tailwind',
  'postcss.config.js': 'postcss',
  'postcss.config.cjs': 'postcss',
  'postcss.config.mjs': 'postcss',
  'unocss.config.ts': 'unocss',
  'panda.config.ts': 'panda',
  'firebase.json': 'firebase',
  '.firebaserc': 'firebase',
  'netlify.toml': 'netlify',
  'vercel.json': 'vercel',
  'wrangler.toml': 'cloudflare-workers',
  'serverless.yml': 'severless',
  'serverless.yaml': 'severless',
  'drizzle.config.ts': 'drizzle',
  'schema.prisma': 'prisma',
  'shadcn.json': 'shadcn',
  'components.json': 'shadcn',
  'sanity.config.ts': 'sanity',
  'sanity.cli.ts': 'sanity',
  'storybook.config.js': 'storybook',
  'docusaurus.config.js': 'docusaurus',
  'gatsby-config.js': 'gatsby',
  'hugo.toml': 'hugo',
  'hugo.yaml': 'hugo',
  'keystatic.config.ts': 'keystatic',
  'contentlayer.config.ts': 'contentlayer',
  'expo.json': 'expo-config',
  'app.json': 'expo-config',

  dockerfile: 'docker',
  '.dockerignore': 'docker',
  'docker-compose.yml': 'docker',
  'docker-compose.yaml': 'docker',
  'compose.yml': 'docker',
  'compose.yaml': 'docker',
  earthfile: 'earthfile',
  'cmakelists.txt': 'cmake',
  'cmake.txt': 'cmake',
  'gradle.kts': 'gradle',
  'build.gradle': 'gradle',
  'build.gradle.kts': 'gradle',
  'pom.xml': 'java',
  makefile: 'gear',
  gnumakefile: 'gear',
  'pulumi.yaml': 'pulumi',
  'main.tf': 'terraform',
  'terraform.tfstate': 'terraform',

  '.gitignore': 'git',
  '.gitattributes': 'git',
  '.gitmodules': 'git',
  '.gitkeep': 'git',
  '.gitconfig': 'git',
  jenkinsfile: 'jenkins',

  '.babelrc': 'babel',
  '.babelrc.json': 'babel',
  '.babelrc.js': 'babel',
  'babel.config.js': 'babel',
  'babel.config.json': 'babel',
  '.swcrc': 'swc',

  license: 'license',
  'license.md': 'license',
  'license.txt': 'license',
  'readme.md': 'markdown',
  readme: 'markdown',
  'changelog.md': 'markdown',
  'contributing.md': 'markdown',
  'code_of_conduct.md': 'markdown',

  'electron.vite.config.ts': 'vite',
  'electron.vite.config.js': 'vite',
  'electron-builder.yml': 'gear',
  'electron-builder.json': 'gear',
  '.cursorrules': 'cursor',
  '.cursorignore': 'cursor',
  'claude.md': 'claude',
  '.claude.md': 'claude'
}

const FILE_BY_EXT: Record<string, string> = {
  ts: 'ts',
  tsx: 'react-ts',
  js: 'js',
  jsx: 'react',
  mjs: 'js',
  cjs: 'js',
  mts: 'ts',
  cts: 'ts',

  'd.ts': 'dts',
  'test.ts': 'ts-test',
  'test.tsx': 'react-test',
  'test.js': 'js-test',
  'test.jsx': 'react-test',
  'spec.ts': 'ts-test',
  'spec.tsx': 'react-test',
  'spec.js': 'js-test',
  'spec.jsx': 'react-test',
  'types.ts': 'ts-types',
  'css.ts': 'vanilla-extract',

  json: 'code-yellow',
  jsonc: 'code-yellow',
  json5: 'code-yellow',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'gear',
  ini: 'gear',
  cfg: 'gear',
  conf: 'gear',
  env: 'gear',
  xml: 'xml',
  csv: 'csv',
  tsv: 'csv',

  html: 'code-orange',
  htm: 'code-orange',
  css: 'brackets-sky',
  scss: 'sass',
  sass: 'sass',
  less: 'brackets-sky',
  styl: 'stylus',
  vue: 'vue',
  svelte: 'svelte',
  astro: 'astro',
  mdx: 'mdx',
  md: 'markdown',
  markdown: 'markdown',
  pug: 'pug',
  haml: 'haml',
  twig: 'twig',
  liquid: 'liquid',
  ejs: 'code-yellow',
  njk: 'nunjucks',
  jmd: 'julia-markdown',
  svx: 'svx',

  py: 'python',
  rb: 'ruby',
  php: 'php',
  go: 'go',
  rs: 'rust',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  swift: 'swift',
  dart: 'dart',
  c: 'c',
  h: 'h',
  cpp: 'cplus',
  cc: 'cplus',
  cxx: 'cplus',
  hpp: 'h',
  hh: 'h',
  hxx: 'h',
  cs: 'csharp',
  fs: 'fsharp',
  fsx: 'fsharp',
  fsproj: 'fsharp',
  ml: 'ocaml',
  mli: 'ocaml',
  hs: 'haskell',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hrl: 'erlang',
  clj: 'clojure',
  cljs: 'clojure',
  cljc: 'clojure',
  cr: 'crystal',
  zig: 'zig',
  nim: 'nim',
  v: 'v',
  d: 'd',
  lua: 'lua',
  luau: 'luau',
  pl: 'perl',
  pm: 'perl',
  r: 'r',
  jl: 'julia',
  scala: 'scala',
  sbt: 'sbt',
  groovy: 'gradle',
  pkl: 'pkl',
  proto: 'proto',
  sol: 'solidity',
  cu: 'cuda',
  cuh: 'cuda',
  tex: 'tex',
  res: 'rescript',
  resi: 'rescript-interface',
  re: 'rescript',
  rei: 'rescript-interface',
  gleam: 'gleam',
  nix: 'nix',
  asm: 'assembly',
  s: 'assembly',
  coffee: 'coffeescript',
  cfm: 'coldfusion',
  cfc: 'coldfusion',
  for: 'fortran',
  f90: 'fortran',
  razor: 'razor',
  cshtml: 'razor',
  feature: 'cucumber',
  robot: 'robot',
  fnc: 'func',
  func: 'func',

  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  fish: 'shell',
  ps1: 'shell',
  bat: 'shell',
  cmd: 'shell',

  pdf: 'pdf',
  txt: 'text',
  log: 'text',
  ipynb: 'notebook',

  png: 'image',
  jpg: 'image',
  jpeg: 'image',
  webp: 'image',
  gif: 'gif',
  svg: 'svg',
  ico: 'image',
  bmp: 'image',
  avif: 'image',

  mp3: 'audio',
  wav: 'audio',
  ogg: 'audio',
  flac: 'audio',
  m4a: 'audio',
  mp4: 'video',
  mov: 'video',
  webm: 'video',
  mkv: 'video',
  avi: 'video',

  ttf: 'font',
  otf: 'font',
  woff: 'font',
  woff2: 'font',
  eot: 'font',

  zip: 'lock',
  rar: 'lock',
  '7z': 'lock',
  tar: 'lock',
  gz: 'lock',
  tgz: 'lock',
  exe: 'exe',
  dll: 'exe',
  msi: 'exe',

  graphql: 'graphql',
  gql: 'graphql',
  sql: 'database',
  prisma: 'prisma',
  drizzle: 'drizzle',

  http: 'http',
  rest: 'http',
  drawio: 'drawio',
  patch: 'patch',
  diff: 'patch',

  mcmeta: 'minecraft',
  antlers: 'statamic-antlers',
  dune: 'dune'
}


export function folderIcon(name: string, isOpen: boolean): string {
  if (isOpen) return folderUrl('folder-open')
  const key = name.toLowerCase()
  const mapped = FOLDER_BY_NAME[key]
  return folderUrl(mapped ?? 'folder')
}

export function fileIcon(name: string): string {
  const lower = name.toLowerCase()

  if (lower === 'crab.md') return asset('sreda.png')

  if (FILE_BY_NAME[lower]) return fileUrl(FILE_BY_NAME[lower])

  const parts = lower.split('.')

  if (parts.length >= 3) {
    const compound = parts.slice(-2).join('.')
    if (FILE_BY_EXT[compound]) return fileUrl(FILE_BY_EXT[compound])
  }

  const ext = parts.length > 1 ? parts[parts.length - 1] : ''
  if (ext && FILE_BY_EXT[ext]) return fileUrl(FILE_BY_EXT[ext])

  return fileUrl('document')
}
